services:
  - type: web
    name: smart-retail-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this in the Render dashboard for security
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        value: redis://localhost:6379
    autoDeploy: true
    rootDir: server

  - type: static
    name: smart-retail-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: client
    envVars:
      - key: VITE_API_URL
        value: https://smart-retail-backend.onrender.com/api # Update this after backend deploys
      - key: VITE_ML_SERVICE_URL
        value: https://smart-retail-backend.onrender.com/ml
    autoDeploy: true

  - type: web
    name: smart-retail-ml-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    rootDir: ml_service
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/ml_service
      - key: MODEL_PATH
        value: /opt/render/project/src/ml_service/models
    autoDeploy: true 